.TH "Neskol/MaiLib Directory Reference" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neskol/MaiLib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBPMChange\&.cs\fP"
.br
.ti -1c
.RI "file \fBBPMChanges\&.cs\fP"
.br
.ti -1c
.RI "file \fBChart\&.cs\fP"
.br
.ti -1c
.RI "file \fBChartPack\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompiler\&.cs\fP"
.br
.ti -1c
.RI "file \fBHold\&.cs\fP"
.br
.ti -1c
.RI "file \fBIChart\&.cs\fP"
.br
.ti -1c
.RI "file \fBICompiler\&.cs\fP"
.br
.ti -1c
.RI "file \fBINote\&.cs\fP"
.br
.ti -1c
.RI "file \fBIParser\&.cs\fP"
.br
.ti -1c
.RI "file \fBITokenizer\&.cs\fP"
.br
.ti -1c
.RI "file \fBIXmlUtility\&.cs\fP"
.br
.ti -1c
.RI "file \fBMa2\&.cs\fP"
.br
.ti -1c
.RI "file \fBMa2parser\&.cs\fP"
.br
.ti -1c
.RI "file \fBMa2Tokenizer\&.cs\fP"
.br
.ti -1c
.RI "file \fBMeasureChange\&.cs\fP"
.br
.ti -1c
.RI "file \fBMeasureChanges\&.cs\fP"
.br
.ti -1c
.RI "file \fBNote\&.cs\fP"
.br
.ti -1c
.RI "file \fBRest\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimai\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimaiCompiler\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimaiparser\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimaiTokenizer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSlide\&.cs\fP"
.br
.ti -1c
.RI "file \fBTap\&.cs\fP"
.br
.ti -1c
.RI "file \fBTrackInformation\&.cs\fP"
.br
.ti -1c
.RI "file \fBXMaiL\&.cs\fP"
.br
.ti -1c
.RI "file \fBXmlInformation\&.cs\fP"
.br
.in -1c
