.TH "Neskol/MaiLib/obj/Debug/net6.0 Directory Reference" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neskol/MaiLib/obj/Debug/net6.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v6\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBMaiLib\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBMaiLib\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
