.TH "Neskol/MaiLib/ITokenizer.cs" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neskol/MaiLib/ITokenizer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBMaiLib\&.ITokenizer\fP"
.br
.RI "Intake files and tokenize\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMaiLib\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
