.TH "Neskol/MaiLib/Ma2parser.cs" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neskol/MaiLib/Ma2parser.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaiLib\&.Ma2Parser\fP"
.br
.RI "Parses ma2 file into Ma2 chart format\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMaiLib\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMaiLib\&.StdParam\fP { \fBMaiLib\&.Type\fP, \fBMaiLib\&.Bar\fP, \fBMaiLib\&.Tick\fP, \fBMaiLib\&.KeyOrParam\fP, \fBMaiLib\&.WaitTimeOrParam\fP, \fBMaiLib\&.LastTime\fP, \fBMaiLib\&.EndKey\fP }"
.br
.RI "Give enums of parameters of Standard Keys\&. "
.ti -1c
.RI "enum \fBMaiLib\&.DxParam\fP { \fBMaiLib\&.Type\fP, \fBMaiLib\&.Bar\fP, \fBMaiLib\&.Tick\fP, \fBMaiLib\&.Key\fP, \fBMaiLib\&.KeyGroupOrLastTime\fP, \fBMaiLib\&.SpecialEffect\fP, \fBMaiLib\&.NoteSize\fP }"
.br
.RI "Give enums of parameters of Deluxe Keys\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
