.TH "MaiLib.IChart" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.IChart \- Provide interface for charts\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMaiLib\&.Chart\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Updates all information\&. "
.ti -1c
.RI "bool \fBCheckValidity\fP ()"
.br
.RI "Check if this chart is valid\&. "
.ti -1c
.RI "string \fBCompose\fP ()"
.br
.RI "Export this Good Brother\&. "
.ti -1c
.RI "void \fBShiftByOffset\fP (int overallTick)"
.br
.RI "Shift the chart notes by defined overall tick\&. "
.ti -1c
.RI "void \fBShiftByOffset\fP (int bar, int tick)"
.br
.RI "Shift the chart notes by defined overall tick\&. "
.ti -1c
.RI "void \fBRotateNotes\fP (string method)"
.br
.RI "Rotate the notes by specified method\&. "
.ti -1c
.RI "double \fBGetTimeStamp\fP (int bar, int tick)"
.br
.RI "Get appropriate time stamp of given tick\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provide interface for charts\&. 
.PP
Definition at line \fB6\fP of file \fBIChart\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool MaiLib\&.IChart\&.CheckValidity ()"

.PP
Check if this chart is valid\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implemented in \fBMaiLib\&.Chart\fP, \fBMaiLib\&.Ma2\fP, \fBMaiLib\&.Simai\fP, and \fBMaiLib\&.XMaiL\fP\&.
.SS "string MaiLib\&.IChart\&.Compose ()"

.PP
Export this Good Brother\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implemented in \fBMaiLib\&.Chart\fP, \fBMaiLib\&.ChartPack\fP, \fBMaiLib\&.Ma2\fP, \fBMaiLib\&.Simai\fP, and \fBMaiLib\&.XMaiL\fP\&.
.SS "double MaiLib\&.IChart\&.GetTimeStamp (int bar, int tick)"

.PP
Get appropriate time stamp of given tick\&. 
.PP
\fBReturns\fP
.RS 4
Time stamp of bar and note
.RE
.PP
<requires>this\&.bpmChanges!=null</requires> 
.PP
Implemented in \fBMaiLib\&.Chart\fP\&.
.SS "void MaiLib\&.IChart\&.RotateNotes (string method)"

.PP
Rotate the notes by specified method\&. 
.PP
\fBParameters\fP
.RS 4
\fImethod\fP Clockwise90, Clockwise 180, Counterclockwise90, Counterclockwise 180, UpSideDown, LeftToRight
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Chart\fP\&.
.SS "void MaiLib\&.IChart\&.ShiftByOffset (int bar, int tick)"

.PP
Shift the chart notes by defined overall tick\&. 
.PP
\fBParameters\fP
.RS 4
\fIbar\fP Bar to add for offset
.br
\fItick\fP Tick to add for offset
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Chart\fP\&.
.SS "void MaiLib\&.IChart\&.ShiftByOffset (int overallTick)"

.PP
Shift the chart notes by defined overall tick\&. 
.PP
\fBParameters\fP
.RS 4
\fIoverallTick\fP Tick to add for offset
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Chart\fP\&.
.SS "void MaiLib\&.IChart\&.Update ()"

.PP
Updates all information\&. 
.PP
Implemented in \fBMaiLib\&.Chart\fP, and \fBMaiLib\&.XMaiL\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
