.TH "MaiLib.MeasureChanges" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.MeasureChanges \- Store measure change notes in a chart\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeasureChanges\fP ()"
.br
.RI "Construct an empty Measure Change\&. "
.ti -1c
.RI "\fBMeasureChanges\fP (\fBMeasureChanges\fP takeIn)"
.br
.RI "Construct Measure Change with existing one\&. "
.ti -1c
.RI "\fBMeasureChanges\fP (int initialQuaver, int initialBeat)"
.br
.RI "Take in initial quavers and beats, incase MET_CHANGE is not specified\&. "
.ti -1c
.RI "\fBMeasureChanges\fP (List< int > bar, List< int > tick, List< int > quavers, List< int > beats)"
.br
.RI "Construct a measure of given beats\&. "
.ti -1c
.RI "void \fBAdd\fP (int bar, int tick, int quavers, int beats)"
.br
.RI "Add new measure changes to MeasureChanges\&. "
.ti -1c
.RI "bool \fBCheckValidity\fP ()"
.br
.ti -1c
.RI "string \fBCompose\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< int > \fBBar\fP\fC [get]\fP"
.br
.RI "Return this\&.Bar\&. "
.ti -1c
.RI "List< int > \fBTick\fP\fC [get]\fP"
.br
.RI "Return this\&.Tick\&. "
.ti -1c
.RI "List< int > \fBQuavers\fP\fC [get]\fP"
.br
.RI "Return this\&.Quavers\&. "
.ti -1c
.RI "List< int > \fBBeats\fP\fC [get]\fP"
.br
.RI "Return this\&.Beats\&. "
.ti -1c
.RI "List< \fBMeasureChange\fP > \fBChangeNotes\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBInitialChange\fP\fC [get]\fP"
.br
.RI "Return first definitions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Store measure change notes in a chart\&. 
.PP
Definition at line \fB6\fP of file \fBMeasureChanges\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaiLib\&.MeasureChanges\&.MeasureChanges ()"

.PP
Construct an empty Measure Change\&. 
.PP
Definition at line \fB19\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "MaiLib\&.MeasureChanges\&.MeasureChanges (\fBMeasureChanges\fP takeIn)"

.PP
Construct Measure Change with existing one\&. 
.PP
Definition at line \fB31\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "MaiLib\&.MeasureChanges\&.MeasureChanges (int initialQuaver, int initialBeat)"

.PP
Take in initial quavers and beats, incase MET_CHANGE is not specified\&. 
.PP
\fBParameters\fP
.RS 4
\fIinitialQuaver\fP Initial Quaver
.br
\fIinitialBeat\fP Initial Beat
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "MaiLib\&.MeasureChanges\&.MeasureChanges (List< int > bar, List< int > tick, List< int > quavers, List< int > beats)"

.PP
Construct a measure of given beats\&. 
.PP
\fBParameters\fP
.RS 4
\fIbar\fP 
.br
\fItick\fP 
.br
\fIquavers\fP 
.br
\fIbeats\fP 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBMeasureChanges\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MaiLib\&.MeasureChanges\&.Add (int bar, int tick, int quavers, int beats)"

.PP
Add new measure changes to MeasureChanges\&. 
.PP
\fBParameters\fP
.RS 4
\fIbar\fP Bar which changes
.br
\fItick\fP Tick which changes
.br
\fIquavers\fP Quavers which changes
.br
\fIbeats\fP Beat which changes
.RE
.PP

.PP
Definition at line \fB120\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "bool MaiLib\&.MeasureChanges\&.CheckValidity ()"

.PP
Definition at line \fB139\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "string MaiLib\&.MeasureChanges\&.Compose ()"

.PP
Definition at line \fB148\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "void MaiLib\&.MeasureChanges\&.Update ()"

.PP
Definition at line \fB165\fP of file \fBMeasureChanges\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<int> MaiLib\&.MeasureChanges\&.Bar\fC [get]\fP"

.PP
Return this\&.Bar\&. 
.PP
Definition at line \fB77\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "List<int> MaiLib\&.MeasureChanges\&.Beats\fC [get]\fP"

.PP
Return this\&.Beats\&. 
.PP
Definition at line \fB101\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "List<\fBMeasureChange\fP> MaiLib\&.MeasureChanges\&.ChangeNotes\fC [get]\fP"

.PP
Definition at line \fB106\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "string MaiLib\&.MeasureChanges\&.InitialChange\fC [get]\fP"

.PP
Return first definitions\&. 
.PP
Definition at line \fB131\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "List<int> MaiLib\&.MeasureChanges\&.Quavers\fC [get]\fP"

.PP
Return this\&.Quavers\&. 
.PP
Definition at line \fB93\fP of file \fBMeasureChanges\&.cs\fP\&.
.SS "List<int> MaiLib\&.MeasureChanges\&.Tick\fC [get]\fP"

.PP
Return this\&.Tick\&. 
.PP
Definition at line \fB85\fP of file \fBMeasureChanges\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
