.TH "MaiLib" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBPMChange\fP"
.br
.RI "BPMChange note for Simai\&. "
.ti -1c
.RI "class \fBBPMChanges\fP"
.br
.ti -1c
.RI "class \fBChart\fP"
.br
.RI "A class holding notes and information to form a chart\&. "
.ti -1c
.RI "class \fBChartPack\fP"
.br
.RI "Construct a collection to store charts in relate of SD and DX\&. "
.ti -1c
.RI "class \fBCompiler\fP"
.br
.ti -1c
.RI "class \fBHold\fP"
.br
.RI "Constructs Hold Note\&. "
.ti -1c
.RI "interface \fBIChart\fP"
.br
.RI "Provide interface for charts\&. "
.ti -1c
.RI "interface \fBICompiler\fP"
.br
.RI "Provide interface for Compilers\&. "
.ti -1c
.RI "interface \fBINote\fP"
.br
.RI "Provide interface and basic functions for Notes\&. "
.ti -1c
.RI "interface \fBIParser\fP"
.br
.RI "Provide interface for parsers\&. "
.ti -1c
.RI "interface \fBITokenizer\fP"
.br
.RI "Intake files and tokenize\&. "
.ti -1c
.RI "interface \fBIXmlUtility\fP"
.br
.RI "Provide handful methods for Xml\&. "
.ti -1c
.RI "class \fBMa2\fP"
.br
.RI "Implementation of chart in ma2 format\&. "
.ti -1c
.RI "class \fBMa2Parser\fP"
.br
.RI "Parses ma2 file into Ma2 chart format\&. "
.ti -1c
.RI "class \fBMa2Tokenizer\fP"
.br
.RI "Tokenizer of ma2 file\&. "
.ti -1c
.RI "class \fBMeasureChange\fP"
.br
.RI "Defines measure change note that indicates a measure change in bar\&. "
.ti -1c
.RI "class \fBMeasureChanges\fP"
.br
.RI "Store measure change notes in a chart\&. "
.ti -1c
.RI "class \fBNote\fP"
.br
.RI "Basic note\&. "
.ti -1c
.RI "class \fBRest\fP"
.br
.RI "Construct Rest Note solely for Simai\&. "
.ti -1c
.RI "class \fBSimai\fP"
.br
.ti -1c
.RI "class \fBSimaiCompiler\fP"
.br
.RI "Compile various Ma2 Charts\&. "
.ti -1c
.RI "class \fBSimaiParser\fP"
.br
.RI "Parse charts in Simai format\&. "
.ti -1c
.RI "class \fBSimaiTokenizer\fP"
.br
.RI "Tokenize input file into tokens that parser can read\&. "
.ti -1c
.RI "class \fBSlide\fP"
.br
.RI "Construct a Slide note (With START!) "
.ti -1c
.RI "class \fBTrackInformation\fP"
.br
.RI "Use xml to store track information\&. "
.ti -1c
.RI "class \fBXMaiL\fP"
.br
.RI "Using xml to store maicharts\&. "
.ti -1c
.RI "class \fBXmlInformation\fP"
.br
.RI "Using Xml to store trackInformation\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStdParam\fP { \fBType\fP, \fBBar\fP, \fBTick\fP, \fBKeyOrParam\fP, \fBWaitTimeOrParam\fP, \fBLastTime\fP, \fBEndKey\fP }"
.br
.RI "Give enums of parameters of Standard Keys\&. "
.ti -1c
.RI "enum \fBDxParam\fP { \fBType\fP, \fBBar\fP, \fBTick\fP, \fBKey\fP, \fBKeyGroupOrLastTime\fP, \fBSpecialEffect\fP, \fBNoteSize\fP }"
.br
.RI "Give enums of parameters of Deluxe Keys\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMaiLib\&.DxParam\fP"

.PP
Give enums of parameters of Deluxe Keys\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIType \fP\fP
.TP
\fB\fIBar \fP\fP
.TP
\fB\fITick \fP\fP
.TP
\fB\fIKey \fP\fP
.TP
\fB\fIKeyGroupOrLastTime \fP\fP
.TP
\fB\fISpecialEffect \fP\fP
.TP
\fB\fINoteSize \fP\fP
.PP
Definition at line \fB12\fP of file \fBMa2parser\&.cs\fP\&.
.SS "enum \fBMaiLib\&.StdParam\fP"

.PP
Give enums of parameters of Standard Keys\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIType \fP\fP
.TP
\fB\fIBar \fP\fP
.TP
\fB\fITick \fP\fP
.TP
\fB\fIKeyOrParam \fP\fP
.TP
\fB\fIWaitTimeOrParam \fP\fP
.TP
\fB\fILastTime \fP\fP
.TP
\fB\fIEndKey \fP\fP
.PP
Definition at line \fB8\fP of file \fBMa2parser\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
