.TH "MaiLib.Ma2Tokenizer" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.Ma2Tokenizer \- Tokenizer of ma2 file\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaiLib\&.ITokenizer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMa2Tokenizer\fP ()"
.br
.RI "Empty Constructor\&. "
.ti -1c
.RI "string[] \fBTokens\fP (string location)"
.br
.RI "Intake files and return tokens\&. "
.ti -1c
.RI "string[] \fBTokensFromText\fP (string text)"
.br
.RI "Intake files and return tokens\&. "
.in -1c
.in +1c
.ti -1c
.RI "string[] \fBTokens\fP (string location)"
.br
.RI "Intake files and return tokens\&. "
.ti -1c
.RI "string[] \fBTokensFromText\fP (string text)"
.br
.RI "Intake files and return tokens\&. "
.in -1c
.SH "Detailed Description"
.PP 
Tokenizer of ma2 file\&. 
.PP
Definition at line \fB6\fP of file \fBMa2Tokenizer\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaiLib\&.Ma2Tokenizer\&.Ma2Tokenizer ()"

.PP
Empty Constructor\&. 
.PP
Definition at line \fB11\fP of file \fBMa2Tokenizer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string[] MaiLib\&.Ma2Tokenizer\&.Tokens (string location)"

.PP
Intake files and return tokens\&. 
.PP
\fBParameters\fP
.RS 4
\fIlocation\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Tokens from file specified
.RE
.PP

.PP
Implements \fBMaiLib\&.ITokenizer\fP\&.
.PP
Definition at line \fB15\fP of file \fBMa2Tokenizer\&.cs\fP\&.
.SS "string[] MaiLib\&.Ma2Tokenizer\&.TokensFromText (string text)"

.PP
Intake files and return tokens\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Tokens from text specified
.RE
.PP

.PP
Implements \fBMaiLib\&.ITokenizer\fP\&.
.PP
Definition at line \fB21\fP of file \fBMa2Tokenizer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
