.TH "MaiLib.SimaiCompiler" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.SimaiCompiler \- Compile various Ma2 Charts\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaiLib\&.Compiler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimaiCompiler\fP (string location, string targetLocation)"
.br
.RI "Construct compiler of a single song\&. "
.ti -1c
.RI "\fBSimaiCompiler\fP (string location, string targetLocation, bool forUtage)"
.br
.RI "Construct compiler of a single song\&. "
.ti -1c
.RI "\fBSimaiCompiler\fP ()"
.br
.RI "Empty constructor\&. "
.ti -1c
.RI "override string \fBCompose\fP ()"
.br
.RI "Compose given chart to specific format\&. "
.ti -1c
.RI "override string \fBCompose\fP (\fBChart\fP chart)"
.br
.RI "Return compose of specified chart\&. "
.ti -1c
.RI "override string \fBCompose\fP (bool isUtage, List< string > ma2files)"
.br
.RI "Compose utage Charts\&. "
.in -1c

Public Member Functions inherited from \fBMaiLib\&.Compiler\fP
.in +1c
.ti -1c
.RI "\fBCompiler\fP (string location, string targetLocation)"
.br
.RI "Construct compiler of a single song\&. "
.ti -1c
.RI "\fBCompiler\fP ()"
.br
.RI "Empty constructor\&. "
.ti -1c
.RI "bool \fBCheckValidity\fP ()"
.br
.RI "Check if the chart given is valid to print\&. "
.ti -1c
.RI "abstract string \fBCompose\fP ()"
.br
.RI "Compose given chart to specific format\&. "
.ti -1c
.RI "abstract string \fBCompose\fP (\fBChart\fP chart)"
.br
.RI "Return compose of specified chart\&. "
.ti -1c
.RI "abstract string \fBCompose\fP (bool isUtage, List< string > ma2files)"
.br
.RI "Compose utage charts\&. "
.ti -1c
.RI "void \fBTakeInformation\fP (Dictionary< string, string > information)"
.br
.RI "Intake information to compile data\&. "
.ti -1c
.RI "\fBBPMChanges\fP \fBSymbolicBPMTable\fP ()"
.br
.RI "Return the chart bpm change table of MaiCompiler\&. "
.ti -1c
.RI "\fBNote\fP \fBSymbolicFirstNote\fP (bool isUtage)"
.br
.RI "Return the first note of master chart\&. "
.ti -1c
.RI "string \fBGenerateOneLineSummary\fP ()"
.br
.RI "Generate one line summary of this track with ID, name, genre and difficulty\&. "
.in -1c
.in +1c
.ti -1c
.RI "void \fBTakeInformation\fP (Dictionary< string, string > information)"
.br
.RI "Intake information to compile data\&. "
.ti -1c
.RI "string \fBCompose\fP ()"
.br
.RI "Compose given chart to specific format\&. "
.ti -1c
.RI "bool \fBCheckValidity\fP ()"
.br
.RI "Check if the chart given is valid to print\&. "
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBMaiLib\&.Compiler\fP
.in +1c
.ti -1c
.RI "static readonly string[] \fBdifficulty\fP = { 'Easy', 'Basic', 'Advanced', 'Expert', 'Master', 'Remaster', 'Utage' }"
.br
.RI "Stores difficulty keywords\&. "
.in -1c

Properties inherited from \fBMaiLib\&.Compiler\fP
.in +1c
.ti -1c
.RI "string \fBGlobalSep\fP\fC [get]\fP"
.br
.RI "Access the path separator\&. "
.ti -1c
.RI "List< string > \fBCompiledChart\fP\fC [get, set]\fP"
.br
.RI "Stores the information of Compiled Chart\&. "
.ti -1c
.RI "List< \fBChart\fP > \fBCharts\fP\fC [get, set]\fP"
.br
.RI "Access stored charts\&. "
.ti -1c
.RI "Dictionary< string, string > \fBInformation\fP\fC [get, set]\fP"
.br
.RI "Access global information\&. "
.ti -1c
.RI "\fBXmlInformation\fP \fBMusicXml\fP\fC [get, set]\fP"
.br
.RI "Access read in music XML file\&. "
.ti -1c
.RI "string[] \fBDifficulty\fP\fC [get]\fP"
.br
.RI "Access difficulty;\&. "
.ti -1c
.RI "Dictionary< string, string > \fBRotateDictionary\fP\fC [get, set]\fP"
.br
.RI "Access the rotate dictionary\&. "
.in -1c
.SH "Detailed Description"
.PP 
Compile various Ma2 Charts\&. 
.PP
Definition at line \fB11\fP of file \fBSimaiCompiler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaiLib\&.SimaiCompiler\&.SimaiCompiler (string location, string targetLocation)"

.PP
Construct compiler of a single song\&. 
.PP
\fBParameters\fP
.RS 4
\fIlocation\fP Folder
.br
\fItargetLocation\fP Output folder
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBSimaiCompiler\&.cs\fP\&.
.SS "MaiLib\&.SimaiCompiler\&.SimaiCompiler (string location, string targetLocation, bool forUtage)"

.PP
Construct compiler of a single song\&. 
.PP
\fBParameters\fP
.RS 4
\fIlocation\fP Folder
.br
\fItargetLocation\fP Output folder
.br
\fIforUtage\fP True if for utage
.RE
.PP

.PP
Definition at line \fB74\fP of file \fBSimaiCompiler\&.cs\fP\&.
.SS "MaiLib\&.SimaiCompiler\&.SimaiCompiler ()"

.PP
Empty constructor\&. 
.PP
Definition at line \fB115\fP of file \fBSimaiCompiler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string MaiLib\&.SimaiCompiler\&.Compose ()\fC [virtual]\fP"

.PP
Compose given chart to specific format\&. 
.PP
\fBReturns\fP
.RS 4
Corresponding chart
.RE
.PP

.PP
Implements \fBMaiLib\&.Compiler\fP\&.
.PP
Definition at line \fB126\fP of file \fBSimaiCompiler\&.cs\fP\&.
.SS "override string MaiLib\&.SimaiCompiler\&.Compose (bool isUtage, List< string > ma2files)\fC [virtual]\fP"

.PP
Compose utage Charts\&. 
.PP
\fBParameters\fP
.RS 4
\fIisUtage\fP switch to produce utage
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding utage chart
.RE
.PP

.PP
Implements \fBMaiLib\&.Compiler\fP\&.
.PP
Definition at line \fB241\fP of file \fBSimaiCompiler\&.cs\fP\&.
.SS "override string MaiLib\&.SimaiCompiler\&.Compose (\fBChart\fP chart)\fC [virtual]\fP"

.PP
Return compose of specified chart\&. 
.PP
\fBParameters\fP
.RS 4
\fIchart\fP Chart to compose
.RE
.PP
\fBReturns\fP
.RS 4
Maidata of specified chart WITHOUT headers
.RE
.PP

.PP
Implements \fBMaiLib\&.Compiler\fP\&.
.PP
Definition at line \fB231\fP of file \fBSimaiCompiler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
