.TH "MaiLib.Ma2Parser" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.Ma2Parser \- Parses ma2 file into Ma2 chart format\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaiLib\&.IParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMa2Parser\fP ()"
.br
.RI "Empty constructor\&. "
.ti -1c
.RI "\fBChart\fP \fBChartOfToken\fP (string[] token)"
.br
.RI "Return correct GoodBrother of given Token\&. "
.ti -1c
.RI "\fBBPMChanges\fP \fBBPMChangesOfToken\fP (string token)"
.br
.RI "Return correct BPMChanges of given Token\&. "
.ti -1c
.RI "\fBMeasureChanges\fP \fBMeasureChangesOfToken\fP (string token)"
.br
.RI "Return corresponding MeasureChanges\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"
.br
.RI "Return correct Slide note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token)"
.br
.RI "Return correct Slide note\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token)"
.br
.RI "Return correct Tap note\&. "
.in -1c
.in +1c
.ti -1c
.RI "\fBChart\fP \fBChartOfToken\fP (string[] token)"
.br
.RI "Return correct GoodBrother of given Token\&. "
.ti -1c
.RI "\fBBPMChanges\fP \fBBPMChangesOfToken\fP (string token)"
.br
.RI "Return correct BPMChanges of given Token\&. "
.ti -1c
.RI "\fBMeasureChanges\fP \fBMeasureChangesOfToken\fP (string token)"
.br
.RI "Return corresponding MeasureChanges\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"
.br
.RI "Return correct Slide note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token)"
.br
.RI "Return correct Slide note\&. "
.in -1c
.SH "Detailed Description"
.PP 
Parses ma2 file into Ma2 chart format\&. 
.PP
Definition at line \fB16\fP of file \fBMa2parser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaiLib\&.Ma2Parser\&.Ma2Parser ()"

.PP
Empty constructor\&. 
.PP
Definition at line \fB22\fP of file \fBMa2parser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBPMChanges\fP MaiLib\&.Ma2Parser\&.BPMChangesOfToken (string token)"

.PP
Return correct BPMChanges of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to intake
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding BPMChanges
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB128\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBChart\fP MaiLib\&.Ma2Parser\&.ChartOfToken (string[] token)"

.PP
Return correct GoodBrother of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to intake
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding GoodBrother
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB27\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBHold\fP MaiLib\&.Ma2Parser\&.HoldOfToken (string token)"

.PP
Return correct Hold note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Hold Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB275\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBHold\fP MaiLib\&.Ma2Parser\&.HoldOfToken (string token, int bar, int tick, double bpm)"

.PP
Return correct Hold note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Hold Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB242\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBMeasureChanges\fP MaiLib\&.Ma2Parser\&.MeasureChangesOfToken (string token)"

.PP
Return corresponding MeasureChanges\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Intake token
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding measure change
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB133\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBNote\fP MaiLib\&.Ma2Parser\&.NoteOfToken (string token)"

.PP
Return a specific note of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB138\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBNote\fP MaiLib\&.Ma2Parser\&.NoteOfToken (string token, int bar, int tick, double bpm)"

.PP
Return a specific note of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP 
.br
\fItick\fP 
.br
\fIbpm\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Specific Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB192\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBSlide\fP MaiLib\&.Ma2Parser\&.SlideOfToken (string token)"

.PP
Return correct Slide note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Slide Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB332\fP of file \fBMa2parser\&.cs\fP\&.
.SS "\fBSlide\fP MaiLib\&.Ma2Parser\&.SlideOfToken (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"

.PP
Return correct Slide note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIslideStart\fP The start note of this slide
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Slide Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB307\fP of file \fBMa2parser\&.cs\fP\&.
.SS "Tap MaiLib\&.Ma2Parser\&.TapOfToken (string token)"

.PP
Return correct Tap note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Tap
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB390\fP of file \fBMa2parser\&.cs\fP\&.
.SS "Tap MaiLib\&.Ma2Parser\&.TapOfToken (string token, int bar, int tick, double bpm)"

.PP
Return correct Tap note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Tap
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB358\fP of file \fBMa2parser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
