.TH "MaiLib.Simai" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.Simai
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaiLib\&.Chart\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimai\fP ()"
.br
.RI "Empty constructor\&. "
.ti -1c
.RI "\fBSimai\fP (string location)"
.br
.RI "Constructs Simai chart directly from path specified\&. "
.ti -1c
.RI "\fBSimai\fP (List< \fBNote\fP > notes, \fBBPMChanges\fP bpmChanges, \fBMeasureChanges\fP measureChanges)"
.br
.RI "Construct Simai from given parameters\&. "
.ti -1c
.RI "\fBSimai\fP (\fBChart\fP takenIn)"
.br
.ti -1c
.RI "override string \fBCompose\fP ()"
.br
.RI "Compose chart in appropriate result\&. "
.ti -1c
.RI "override bool \fBCheckValidity\fP ()"
.br
.RI "Check if this chart is valid\&. "
.ti -1c
.RI "override string \fBCompose\fP (\fBBPMChanges\fP bpm, \fBMeasureChanges\fP measure)"
.br
.RI "Reconstruct the chart with given arrays\&. "
.in -1c

Public Member Functions inherited from \fBMaiLib\&.Chart\fP
.in +1c
.ti -1c
.RI "\fBChart\fP ()"
.br
.RI "Empty constructor\&. "
.ti -1c
.RI "abstract bool \fBCheckValidity\fP ()"
.br
.RI "Check if this chart is valid\&. "
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.RI "Update properties in Good Brother for exporting\&. "
.ti -1c
.RI "abstract string \fBCompose\fP ()"
.br
.RI "Compose chart in appropriate result\&. "
.ti -1c
.RI "void \fBCheckSlideStart\fP ()"
.br
.RI "Check if all of the slide starts were in the notes\&. "
.ti -1c
.RI "abstract string \fBCompose\fP (\fBBPMChanges\fP bpm, \fBMeasureChanges\fP measure)"
.br
.RI "Override and compose with given arrays\&. "
.ti -1c
.RI "void \fBTakeInformation\fP (Dictionary< string, string > information)"
.br
.RI "Take in and replace the current information\&. "
.ti -1c
.RI "double \fBGetTimeStamp\fP (int bar, int tick)"
.br
.RI "Get appropriate time stamp of given tick\&. "
.ti -1c
.RI "double \fBGetTimeStamp\fP (int overallTick)"
.br
.RI "Give time stamp given overall tick\&. "
.ti -1c
.RI "double \fBGetBPMByTick\fP (int overallTick)"
.br
.RI "Return the BPM at certain tick\&. "
.ti -1c
.RI "bool \fBHasBPMChangeInBetween\fP (int startTick, int endTick)"
.br
.RI "Determine if there are BPM change in between ticks\&. "
.ti -1c
.RI "void \fBShiftByOffset\fP (int overallTick)"
.br
.RI "Shift the chart notes by defined overall tick\&. "
.ti -1c
.RI "void \fBShiftByOffset\fP (int bar, int tick)"
.br
.RI "Shift the chart notes by defined overall tick\&. "
.ti -1c
.RI "void \fBRotateNotes\fP (string method)"
.br
.RI "Rotate the notes by specified method\&. "
.in -1c
.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Updates all information\&. "
.ti -1c
.RI "bool \fBCheckValidity\fP ()"
.br
.RI "Check if this chart is valid\&. "
.ti -1c
.RI "string \fBCompose\fP ()"
.br
.RI "Export this Good Brother\&. "
.ti -1c
.RI "void \fBShiftByOffset\fP (int overallTick)"
.br
.RI "Shift the chart notes by defined overall tick\&. "
.ti -1c
.RI "void \fBShiftByOffset\fP (int bar, int tick)"
.br
.RI "Shift the chart notes by defined overall tick\&. "
.ti -1c
.RI "void \fBRotateNotes\fP (string method)"
.br
.RI "Rotate the notes by specified method\&. "
.ti -1c
.RI "double \fBGetTimeStamp\fP (int bar, int tick)"
.br
.RI "Get appropriate time stamp of given tick\&. "
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBMaiLib\&.Chart\fP
.in +1c
.ti -1c
.RI "static int \fBCalculateLeastMeasure\fP (List< \fBNote\fP > bar)"
.br
.RI "Return the least none 0 measure of bar\&. "
.ti -1c
.RI "static int \fBRealNoteNumber\fP (List< \fBNote\fP > \fBBar\fP)"
.br
.RI "Return note number except Rest, BPM and Measure\&. "
.ti -1c
.RI "static bool \fBContainNotes\fP (List< \fBNote\fP > \fBBar\fP)"
.br
.RI "Judges if this bar contains notes\&. "
.ti -1c
.RI "static int \fBCalculateQuaver\fP (int length)"
.br
.RI "Generate appropriate length for hold and slide\&. "
.ti -1c
.RI "static List< \fBNote\fP > \fBFinishBar\fP (List< \fBNote\fP > bar, List< \fBBPMChange\fP > bpmChanges, int barNumber, int minimalQuaver)"
.br
.RI "Finish Bar writing byu adding specific rest note in between\&. "
.ti -1c
.RI "static int \fBGCD\fP (int a, int b)"
.br
.RI "Return GCD of A and B\&. "
.ti -1c
.RI "static bool \fBIsPrime\fP (int number)"
.br
.RI "Return if this is a prime (1 counts) "
.ti -1c
.RI "static double \fBGetTimeStamp\fP (\fBBPMChanges\fP bpmChanges, int overallTick)"
.br
.RI "Give time stamp given overall tick\&. "
.ti -1c
.RI "static double \fBGetBPMTimeUnit\fP (double bpm)"
.br
.RI "Return BPM tick unit of given bpm\&. "
.ti -1c
.RI "static string \fBGetNoteDetail\fP (\fBBPMChanges\fP bpmChanges, \fBNote\fP inTake)"
.br
.RI "For debug use: print out the note's time stamp in given bpm changes\&. "
.in -1c

Properties inherited from \fBMaiLib\&.Chart\fP
.in +1c
.ti -1c
.RI "List< \fBNote\fP > \fBNotes\fP\fC [get, set]\fP"
.br
.RI "Access to Notes\&. "
.ti -1c
.RI "List< List< \fBNote\fP > > \fBStoredChart\fP\fC [get, set]\fP"
.br
.RI "Returns this\&.Chart\&. aka List of bars\&. "
.ti -1c
.RI "\fBBPMChanges\fP \fBBPMChanges\fP\fC [get, set]\fP"
.br
.RI "Access to BPM Changes\&. "
.ti -1c
.RI "\fBMeasureChanges\fP \fBMeasureChanges\fP\fC [get, set]\fP"
.br
.RI "Access to Measure Changes\&. "
.ti -1c
.RI "int \fBTapNumber\fP\fC [get, set]\fP"
.br
.RI "Access to Tap Number\&. "
.ti -1c
.RI "int \fBBreakNumber\fP\fC [get, set]\fP"
.br
.RI "Access to Break Number\&. "
.ti -1c
.RI "int \fBHoldNumber\fP\fC [get, set]\fP"
.br
.RI "Access to Hold Number\&. "
.ti -1c
.RI "int \fBSlideNumber\fP\fC [get, set]\fP"
.br
.RI "Access to Slide Number\&. "
.ti -1c
.RI "int \fBTouchNumber\fP\fC [get, set]\fP"
.br
.RI "Access to Touch Number\&. "
.ti -1c
.RI "int \fBThoNumber\fP\fC [get, set]\fP"
.br
.RI "Access to Touch Hold Number\&. "
.ti -1c
.RI "int \fBTotalNoteNumber\fP\fC [get]\fP"
.br
.RI "Access to the total note number\&. "
.ti -1c
.RI "int[] \fBUnitScore\fP\fC [get]\fP"
.br
.RI "Access to Unit Score\&. "
.ti -1c
.RI "int \fBAchievement\fP\fC [get, set]\fP"
.br
.RI "Access to theoretical Achievement\&. "
.ti -1c
.RI "int \fBTotalDelay\fP\fC [get, set]\fP"
.br
.RI "Return the total delayed value of this Chart\&. "
.ti -1c
.RI "Dictionary< string, string > \fBInformation\fP\fC [get, set]\fP"
.br
.RI "Return Information\&. "
.ti -1c
.RI "bool \fBIsDXChart\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNote\fP? \fBFirstNote\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBDefinition\fP\fC [get, set]\fP"
.br
.RI "Access the definition of this chart, default by 384\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSimai\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaiLib\&.Simai\&.Simai ()"

.PP
Empty constructor\&. 
.PP
Definition at line \fB10\fP of file \fBSimai\&.cs\fP\&.
.SS "MaiLib\&.Simai\&.Simai (string location)"

.PP
Constructs Simai chart directly from path specified\&. 
.PP
\fBParameters\fP
.RS 4
\fIlocation\fP 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBSimai\&.cs\fP\&.
.SS "MaiLib\&.Simai\&.Simai (List< \fBNote\fP > notes, \fBBPMChanges\fP bpmChanges, \fBMeasureChanges\fP measureChanges)"

.PP
Construct Simai from given parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fInotes\fP Notes to take in
.br
\fIbpmChanges\fP BPM change to take in
.br
\fImeasureChanges\fP Measure change to take in
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBSimai\&.cs\fP\&.
.SS "MaiLib\&.Simai\&.Simai (\fBChart\fP takenIn)"

.PP
Definition at line \fB51\fP of file \fBSimai\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool MaiLib\&.Simai\&.CheckValidity ()\fC [virtual]\fP"

.PP
Check if this chart is valid\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implements \fBMaiLib\&.Chart\fP\&.
.PP
Definition at line \fB216\fP of file \fBSimai\&.cs\fP\&.
.SS "override string MaiLib\&.Simai\&.Compose ()\fC [virtual]\fP"

.PP
Compose chart in appropriate result\&. 
.PP
\fBReturns\fP
.RS 4
String of chart compiled
.RE
.PP

.PP
Implements \fBMaiLib\&.Chart\fP\&.
.PP
Definition at line \fB61\fP of file \fBSimai\&.cs\fP\&.
.SS "override string MaiLib\&.Simai\&.Compose (\fBBPMChanges\fP bpm, \fBMeasureChanges\fP measure)\fC [virtual]\fP"

.PP
Reconstruct the chart with given arrays\&. 
.PP
\fBParameters\fP
.RS 4
\fIbpm\fP New BPM Changes
.br
\fImeasure\fP New Measure Changes
.RE
.PP
\fBReturns\fP
.RS 4
New Composed Chart
.RE
.PP

.PP
Implements \fBMaiLib\&.Chart\fP\&.
.PP
Definition at line \fB229\fP of file \fBSimai\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
