.TH "MaiLib.INote" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.INote \- Provide interface and basic functions for Notes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMaiLib\&.Note\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBCompose\fP (int format)"
.br
.RI "Convert note to string for writing\&. "
.ti -1c
.RI "bool \fBCheckValidity\fP ()"
.br
.RI "See if current note has all information needed\&. "
.ti -1c
.RI "bool \fBUpdate\fP ()"
.br
.RI "Updates this note instance\&. "
.ti -1c
.RI "void \fBFlip\fP (string method)"
.br
.RI "Flip the note according to the method specified\&. "
.ti -1c
.RI "double \fBGetTimeStamp\fP (int overallTick)"
.br
.RI "Give time stamp given overall tick\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provide interface and basic functions for Notes\&. 
.PP
Definition at line \fB6\fP of file \fBINote\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool MaiLib\&.INote\&.CheckValidity ()"

.PP
See if current note has all information needed\&. 
.PP
\fBReturns\fP
.RS 4
True if qualified, false otherwise
.RE
.PP

.PP
Implemented in \fBMaiLib\&.BPMChange\fP, \fBMaiLib\&.Hold\fP, \fBMaiLib\&.MeasureChange\fP, \fBMaiLib\&.Note\fP, and \fBMaiLib\&.Slide\fP\&.
.SS "string MaiLib\&.INote\&.Compose (int format)"

.PP
Convert note to string for writing\&. 
.PP
\fBParameters\fP
.RS 4
\fIformat\fP 0 if Simai, 1 if Ma2
.RE
.PP

.PP
Implemented in \fBMaiLib\&.BPMChange\fP, \fBMaiLib\&.Hold\fP, \fBMaiLib\&.MeasureChange\fP, \fBMaiLib\&.Note\fP, and \fBMaiLib\&.Slide\fP\&.
.SS "void MaiLib\&.INote\&.Flip (string method)"

.PP
Flip the note according to the method specified\&. 
.PP
\fBParameters\fP
.RS 4
\fImethod\fP UpSideDown, LeftToRight, Clockwise90/180, Counterclockwise90/180
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Note\fP\&.
.SS "double MaiLib\&.INote\&.GetTimeStamp (int overallTick)"

.PP
Give time stamp given overall tick\&. 
.PP
\fBParameters\fP
.RS 4
\fIoverallTick\fP Note\&.Bar*384+Note\&.Tick
.RE
.PP
\fBReturns\fP
.RS 4
Appropriate time stamp in seconds
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Note\fP\&.
.SS "bool MaiLib\&.INote\&.Update ()"

.PP
Updates this note instance\&. 
.PP
\fBReturns\fP
.RS 4
True if Calculated Times is defined, false otherwise
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Note\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
