.TH "MaiLib.ITokenizer" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.ITokenizer \- Intake files and tokenize\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMaiLib\&.Ma2Tokenizer\fP, and \fBMaiLib\&.SimaiTokenizer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string[] \fBTokens\fP (string location)"
.br
.RI "Intake files and return tokens\&. "
.ti -1c
.RI "string[] \fBTokensFromText\fP (string text)"
.br
.RI "Intake files and return tokens\&. "
.in -1c
.SH "Detailed Description"
.PP 
Intake files and tokenize\&. 
.PP
Definition at line \fB6\fP of file \fBITokenizer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string[] MaiLib\&.ITokenizer\&.Tokens (string location)"

.PP
Intake files and return tokens\&. 
.PP
\fBParameters\fP
.RS 4
\fIlocation\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Tokens from file specified
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Tokenizer\fP, and \fBMaiLib\&.SimaiTokenizer\fP\&.
.SS "string[] MaiLib\&.ITokenizer\&.TokensFromText (string text)"

.PP
Intake files and return tokens\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Tokens from text specified
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Tokenizer\fP, and \fBMaiLib\&.SimaiTokenizer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
