.TH "Neskol/MaiLib/obj/Debug/net6.0/MaiLib.AssemblyInfo.cs" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neskol/MaiLib/obj/Debug/net6.0/MaiLib.AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
