.TH "MaiLib.IParser" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.IParser \- Provide interface for parsers\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChart\fP \fBChartOfToken\fP (string[] token)"
.br
.RI "Return correct GoodBrother of given Token\&. "
.ti -1c
.RI "\fBBPMChanges\fP \fBBPMChangesOfToken\fP (string token)"
.br
.RI "Return correct BPMChanges of given Token\&. "
.ti -1c
.RI "\fBMeasureChanges\fP \fBMeasureChangesOfToken\fP (string token)"
.br
.RI "Return corresponding MeasureChanges\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"
.br
.RI "Return correct Slide note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token)"
.br
.RI "Return correct Slide note\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provide interface for parsers\&. 
.PP
Definition at line \fB8\fP of file \fBIParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBPMChanges\fP MaiLib\&.IParser\&.BPMChangesOfToken (string token)"

.PP
Return correct BPMChanges of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to intake
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding BPMChanges
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBChart\fP MaiLib\&.IParser\&.ChartOfToken (string[] token)"

.PP
Return correct GoodBrother of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to intake
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding GoodBrother
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBHold\fP MaiLib\&.IParser\&.HoldOfToken (string token)"

.PP
Return correct Hold note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Hold Note
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBHold\fP MaiLib\&.IParser\&.HoldOfToken (string token, int bar, int tick, double bpm)"

.PP
Return correct Hold note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Hold Note
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBMeasureChanges\fP MaiLib\&.IParser\&.MeasureChangesOfToken (string token)"

.PP
Return corresponding MeasureChanges\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Intake token
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding measure change
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBNote\fP MaiLib\&.IParser\&.NoteOfToken (string token)"

.PP
Return a specific note of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Note
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBNote\fP MaiLib\&.IParser\&.NoteOfToken (string token, int bar, int tick, double bpm)"

.PP
Return a specific note of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP 
.br
\fItick\fP 
.br
\fIbpm\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Specific Note
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBSlide\fP MaiLib\&.IParser\&.SlideOfToken (string token)"

.PP
Return correct Slide note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Slide Note
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "\fBSlide\fP MaiLib\&.IParser\&.SlideOfToken (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"

.PP
Return correct Slide note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIslideStart\fP The start note of this slide
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Slide Note
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "Tap MaiLib\&.IParser\&.TapOfToken (string token)"

.PP
Return correct Tap note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Tap
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.
.SS "Tap MaiLib\&.IParser\&.TapOfToken (string token, int bar, int tick, double bpm)"

.PP
Return correct Tap note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Tap
.RE
.PP

.PP
Implemented in \fBMaiLib\&.Ma2Parser\fP, and \fBMaiLib\&.SimaiParser\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
