.TH "MaiLib.SimaiTokenizer" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.SimaiTokenizer \- Tokenize input file into tokens that parser can read\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaiLib\&.ITokenizer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimaiTokenizer\fP ()"
.br
.RI "Constructs a tokenizer\&. "
.ti -1c
.RI "void \fBUpdateFromText\fP (string input)"
.br
.RI "Update candidates from texts specified\&. "
.ti -1c
.RI "void \fBUpdateFromPath\fP (string path)"
.br
.RI "Update candidates from texts specified\&. "
.ti -1c
.RI "string[] \fBTokens\fP (string location)"
.br
.RI "Intake files and return tokens\&. "
.ti -1c
.RI "string[] \fBTokensFromText\fP (string text)"
.br
.RI "Intake files and return tokens\&. "
.in -1c
.in +1c
.ti -1c
.RI "string[] \fBTokens\fP (string location)"
.br
.RI "Intake files and return tokens\&. "
.ti -1c
.RI "string[] \fBTokensFromText\fP (string text)"
.br
.RI "Intake files and return tokens\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< string, string[]> \fBChartCandidates\fP\fC [get]\fP"
.br
.RI "Access the chart candidates\&. "
.in -1c
.SH "Detailed Description"
.PP 
Tokenize input file into tokens that parser can read\&. 
.PP
Definition at line \fB11\fP of file \fBSimaiTokenizer\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaiLib\&.SimaiTokenizer\&.SimaiTokenizer ()"

.PP
Constructs a tokenizer\&. 
.PP
Definition at line \fB26\fP of file \fBSimaiTokenizer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string[] MaiLib\&.SimaiTokenizer\&.Tokens (string location)"

.PP
Intake files and return tokens\&. 
.PP
\fBParameters\fP
.RS 4
\fIlocation\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Tokens from file specified
.RE
.PP

.PP
Implements \fBMaiLib\&.ITokenizer\fP\&.
.PP
Definition at line \fB224\fP of file \fBSimaiTokenizer\&.cs\fP\&.
.SS "string[] MaiLib\&.SimaiTokenizer\&.TokensFromText (string text)"

.PP
Intake files and return tokens\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Tokens from text specified
.RE
.PP

.PP
Implements \fBMaiLib\&.ITokenizer\fP\&.
.PP
Definition at line \fB237\fP of file \fBSimaiTokenizer\&.cs\fP\&.
.SS "void MaiLib\&.SimaiTokenizer\&.UpdateFromPath (string path)"

.PP
Update candidates from texts specified\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP Location of text to be tokenized
.RE
.PP

.PP
Definition at line \fB213\fP of file \fBSimaiTokenizer\&.cs\fP\&.
.SS "void MaiLib\&.SimaiTokenizer\&.UpdateFromText (string input)"

.PP
Update candidates from texts specified\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP Text to be tokenized
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBSimaiTokenizer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<string, string[]> MaiLib\&.SimaiTokenizer\&.ChartCandidates\fC [get]\fP"

.PP
Access the chart candidates\&. 
.PP
Definition at line \fB35\fP of file \fBSimaiTokenizer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
