.TH "MaiLib.SimaiParser" 3 "Sun Feb 5 2023" "Version 1.0.4.0" "MaiLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaiLib.SimaiParser \- Parse charts in Simai format\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaiLib\&.IParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimaiParser\fP ()"
.br
.RI "Constructor of simaiparser\&. "
.ti -1c
.RI "\fBBPMChanges\fP \fBBPMChangesOfToken\fP (string token)"
.br
.RI "Parse BPM change notes\&. "
.ti -1c
.RI "\fBChart\fP \fBChartOfToken\fP (string[] tokens)"
.br
.RI "Return correct GoodBrother of given Token\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBMeasureChanges\fP \fBMeasureChangesOfToken\fP (string token)"
.br
.RI "Return corresponding MeasureChanges\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"
.br
.RI "Return correct Slide note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token)"
.br
.RI "Return correct Slide note\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token)"
.br
.RI "Return correct Tap note\&. "
.in -1c
.in +1c
.ti -1c
.RI "\fBChart\fP \fBChartOfToken\fP (string[] token)"
.br
.RI "Return correct GoodBrother of given Token\&. "
.ti -1c
.RI "\fBBPMChanges\fP \fBBPMChangesOfToken\fP (string token)"
.br
.RI "Return correct BPMChanges of given Token\&. "
.ti -1c
.RI "\fBMeasureChanges\fP \fBMeasureChangesOfToken\fP (string token)"
.br
.RI "Return corresponding MeasureChanges\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "\fBNote\fP \fBNoteOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return a specific note of given Token\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "Tap \fBTapOfToken\fP (string token)"
.br
.RI "Return correct Tap note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token, int bar, int tick, double bpm)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBHold\fP \fBHoldOfToken\fP (string token)"
.br
.RI "Return correct Hold note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"
.br
.RI "Return correct Slide note\&. "
.ti -1c
.RI "\fBSlide\fP \fBSlideOfToken\fP (string token)"
.br
.RI "Return correct Slide note\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< string > \fBEachGroupOfToken\fP (string token)"
.br
.RI "Deal with old, out-fashioned and illogical Simai Each Groups\&. "
.ti -1c
.RI "static List< string > \fBExtractParentheses\fP (string token)"
.br
.RI "Deal with annoying and vigours Parentheses grammar of Simai\&. "
.ti -1c
.RI "static List< string > \fBExtractEachSlides\fP (string token)"
.br
.RI "Deal with annoying and vigours Slide grammar of Simai\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBMaximumDefinition\fP = 384"
.br
.RI "The maximum definition of a chart\&. "
.in -1c
.SH "Detailed Description"
.PP 
Parse charts in Simai format\&. 
.PP
Definition at line \fB9\fP of file \fBSimaiparser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MaiLib\&.SimaiParser\&.SimaiParser ()"

.PP
Constructor of simaiparser\&. 
.PP
Definition at line \fB21\fP of file \fBSimaiparser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBPMChanges\fP MaiLib\&.SimaiParser\&.BPMChangesOfToken (string token)"

.PP
Parse BPM change notes\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP The parsed set of BPM change
.RE
.PP
\fBReturns\fP
.RS 4
Error: simai does not have this variable
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB31\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBChart\fP MaiLib\&.SimaiParser\&.ChartOfToken (string[] token)"

.PP
Return correct GoodBrother of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to intake
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding GoodBrother
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB36\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "static List< string > MaiLib\&.SimaiParser\&.EachGroupOfToken (string token)\fC [static]\fP"

.PP
Deal with old, out-fashioned and illogical Simai Each Groups\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Tokens that potentially contains each Groups
.RE
.PP
\fBReturns\fP
.RS 4
List of strings that is composed with single note\&.
.RE
.PP

.PP
Definition at line \fB527\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "static List< string > MaiLib\&.SimaiParser\&.ExtractEachSlides (string token)\fC [static]\fP"

.PP
Deal with annoying and vigours Slide grammar of Simai\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token that potentially contains multiple slide note
.RE
.PP
\fBReturns\fP
.RS 4
A list of slides extracts each note
.RE
.PP

.PP
Definition at line \fB641\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "static List< string > MaiLib\&.SimaiParser\&.ExtractParentheses (string token)\fC [static]\fP"

.PP
Deal with annoying and vigours Parentheses grammar of Simai\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token that potentially contains multiple slide note
.RE
.PP
\fBReturns\fP
.RS 4
A list of strings extracts each note
.RE
.PP

.PP
Definition at line \fB587\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBHold\fP MaiLib\&.SimaiParser\&.HoldOfToken (string token)"

.PP
Return correct Hold note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Hold Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB152\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBHold\fP MaiLib\&.SimaiParser\&.HoldOfToken (string token, int bar, int tick, double bpm)"

.PP
Return correct Hold note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Hold Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB92\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBMeasureChanges\fP MaiLib\&.SimaiParser\&.MeasureChangesOfToken (string token)"

.PP
Return corresponding MeasureChanges\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Intake token
.RE
.PP
\fBReturns\fP
.RS 4
Corresponding measure change
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB157\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBNote\fP MaiLib\&.SimaiParser\&.NoteOfToken (string token)"

.PP
Return a specific note of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB162\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBNote\fP MaiLib\&.SimaiParser\&.NoteOfToken (string token, int bar, int tick, double bpm)"

.PP
Return a specific note of given Token\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP 
.br
\fItick\fP 
.br
\fIbpm\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Specific Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB210\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBSlide\fP MaiLib\&.SimaiParser\&.SlideOfToken (string token)"

.PP
Return correct Slide note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Slide Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB454\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "\fBSlide\fP MaiLib\&.SimaiParser\&.SlideOfToken (string token, int bar, int tick, \fBNote\fP slideStart, double bpm)"

.PP
Return correct Slide note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIslideStart\fP The start note of this slide
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Slide Note
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB261\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "Tap MaiLib\&.SimaiParser\&.TapOfToken (string token)"

.PP
Return correct Tap note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.RE
.PP
\fBReturns\fP
.RS 4
Specific Tap
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB517\fP of file \fBSimaiparser\&.cs\fP\&.
.SS "Tap MaiLib\&.SimaiParser\&.TapOfToken (string token, int bar, int tick, double bpm)"

.PP
Return correct Tap note\&. 
.PP
\fBParameters\fP
.RS 4
\fItoken\fP Token to take in
.br
\fIbar\fP Bar of this note
.br
\fItick\fP Tick of this note
.br
\fIbpm\fP BPM of this note
.RE
.PP
\fBReturns\fP
.RS 4
Specific Tap
.RE
.PP

.PP
Implements \fBMaiLib\&.IParser\fP\&.
.PP
Definition at line \fB459\fP of file \fBSimaiparser\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int MaiLib\&.SimaiParser\&.MaximumDefinition = 384\fC [static]\fP"

.PP
The maximum definition of a chart\&. 
.PP
Definition at line \fB14\fP of file \fBSimaiparser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MaiLib from the source code\&.
